<a href="https://colab.research.google.com/github/kevengoncalves-git/tecnicas_adversarias/blob/Edu/Inserir_N_gramas_de_Shap_em_EXE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install Shap

Requirement already satisfied: Shap in /usr/local/lib/python3.11/dist-packages (0.47.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from Shap) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from Shap) (1.15.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from Shap) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from Shap) (2.2.2)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.11/dist-packages (from Shap) (4.67.1)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.11/dist-packages (from Shap) (24.2)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.11/dist-packages (from Shap) (0.0.8)
Requirement already satisfied: numba>=0.54 in /usr/local/lib/python3.11/dist-packages (from Shap) (0.60.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.11/dist-packages (from Shap) (3.1.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from Shap) (4.14.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba>=0.54->Shap) (0.43.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->Shap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->Shap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->Shap) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->Shap) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->Shap) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->Shap) (1.17.0)

#Bibliotecas Importadas

In [2]:
import pandas as pd
import shap
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier, ExtraTreesClassifier
from sklearn.ensemble import VotingClassifier

In [3]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, precision_score, recall_score, f1_score
from sklearn.utils import shuffle
import matplotlib.pyplot as plt

#Importar DataSet

In [4]:
df_test = pd.read_csv('/content/df_test_4gram.csv').drop('Unnamed: 0', axis=1)
df_train = pd.read_csv('/content/df_train_processado_4gram.csv').drop('Unnamed: 0', axis=1)

#Criação do Soft Volting

In [5]:
#melhores resultados 4gramas
lr_clf = LogisticRegression(C=0.1, max_iter=150, solver='liblinear')
ext_clf = ExtraTreesClassifier(criterion='entropy', max_depth=6, n_estimators=250)
ad_clf = AdaBoostClassifier(learning_rate=0.1, n_estimators=300)

sf_clf = VotingClassifier(
    estimators=[('lr', lr_clf), ('ext', ext_clf), ('ad', ad_clf)],
    voting='soft')

In [6]:
modelo = sf_clf

# SHAP

In [7]:
df_test = shuffle(df_test)
df_test

,ID,Filename,RG,Family,this program cannot run,program cannot run dos,cannot run dos mode,idata idata idata idata,run dos mode text,kernel32 dll kernel32 dll,...,chttp www microsoft com,ehttp www microsoft com,com pkiops crl crl0a,pkiops crl crl0a ehttp,crl crl0a ehttp www,com pkiops certs crt0,crl0a ehttp www microsoft,tsh tsh tsh tsh,std allocator std std.1,svwh svwh svwh svwh
319,10186,9bbe6414ce22cb5e19f294004cb5cdbc883479d99629dd...,1,28,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,10028,acereader.exe,0,0,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
472,10339,4fd0c22d92f8bf7a062497867a802bdbab4c802ac10c8b...,1,31,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
301,10168,eeee2a6820eedbe2a37e4c992dc6b3135ee0e340892d2a...,1,33,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
42,10042,setup_IconRestorer.exe,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,10011,DesktopImages3D_x64_Install.exe,0,0,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
329,10196,15560b1e35a3a8612a7ba91d00dea6b8dd6e4f3f857399...,1,28,1,1,1,1,0,0,...,1,1,1,1,1,1,1,0,0,0
402,10269,f7a3a8734c004682201b8873691d684985329be3fcdba9...,1,27,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
53,10053,CareUEyes_setup.exe,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
486,10353,840af927adbfdeb7070e1cf73ed195cf48c8d5f35b6de1...,1,31,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
X, y = df_train.drop(["RG", "Filename", "Family", "ID"], axis=1), df_train['RG']

In [9]:
X_test, y_test = df_test.drop(["RG", "Filename", "Family", "ID"], axis=1), df_test['RG']

In [10]:
y_test.value_counts()

RG
1    385
0    133
Name: count, dtype: int64

In [11]:
modelo.fit(X,y)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=0.1, max_iter=150,
                                                 solver='liblinear')),
                             ('ext',
                              ExtraTreesClassifier(criterion='entropy',
                                                   max_depth=6,
                                                   n_estimators=250)),
                             ('ad',
                              AdaBoostClassifier(learning_rate=0.1,
                                                 n_estimators=300))],
                 voting='soft')

In [12]:
res = modelo.predict(X_test)
print('Acc: ',accuracy_score(y_test,res)*100)
print('Prec: ',precision_score(y_test,res)*100)
print('Rec: ',recall_score(y_test,res)*100)
print('F1: ',f1_score(y_test,res)*100)

Acc:  98.06949806949807
Prec:  97.46835443037975
Rec:  100.0
F1:  98.71794871794873

In [13]:
def comparar_arrays(array1, array2):
  """
  Compara dois arrays de tamanhos iguais e retorna um array booleano com True
  onde os valores comparados são iguais e False onde são diferentes.

  Args:
    array1: O primeiro array.
    array2: O segundo array.

  Returns:
    Um array booleano do mesmo tamanho, indicando as posições com valores iguais (True) e diferentes (False).
  """
  if len(array1) != len(array2):
    raise ValueError("Os arrays devem ter o mesmo tamanho.")

  resultado = []
  for i in range(len(array1)):
    resultado.append(bool(array1[i] != array2[i]))

  return resultado

In [14]:
misclassified = comparar_arrays(modelo.predict(X_test), y_test.values)
print(misclassified)

[False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]

In [ ]:
explainer = shap.Explainer(modelo.predict_proba, X)
shap_values = explainer(X_test, max_evals=4000) # Número ainda não decidido # maior que 3285

PermutationExplainer explainer:   5%|▌         | 26/518 [47:16<16:59:18, 124.31s/it]

In [ ]:
shap_values.base_values[1][1]

In [ ]:
# com predict_proba
shap.plots.decision(shap_values.base_values[1][1],shap_values[...,1].values,
                   highlight=misclassified,
                   features=X_test,
                   feature_display_range=slice(-1, -101, -1),
                    new_base_value=0.5,
                    # xlim=(-0.05,1.05),
                    auto_size_plot = False,
                    title="Valor de saída do modelo",
                    show=False,
                    ignore_warnings=True # Add this argument
                   )
plt.gcf().set_size_inches(6,25)
plt.savefig(f'decision_proba_{modelo.__class__.__name__}_allfamily.pdf', format='pdf', dpi=600, bbox_inches='tight')
plt.show()

In [ ]:
fig = plt.figure()
shap.plots.beeswarm(shap_values[...,1], max_display=101,show = False)
plt.gcf().set_size_inches(6,25)
plt.savefig(f'beeswarm_{modelo.__class__.__name__}_allfamily.pdf', format='pdf', dpi=600, bbox_inches='tight')
plt.show()